In [6]:
import numpy as np
import pandas as pd
from numpy import linalg as LA
from numpy.linalg import norm
from numpy import arccos
from numpy import dot
from numpy.linalg import det
from numpy.linalg import inv
from numpy.linalg import matrix_rank
from scipy.linalg import lu
import string

# Q1

### If $ \vec{a}$ and  $ \vec{b}$ are n-dimensional vectors:
$ \\ $
$ \vec{a} = (a_1\ ,   a_2\ , ...  a_n)$
$ \\ $
$ \vec{b} = (b_1\ ,   b_2\ ,  ...  b_n)$
$\\ $
### then their dot product, $\vec{a} \cdot \vec{b}$ is defined as a scalar, obtained by forming the product of the corresponding coordinates and summing them up:  

$\vec{a} \cdot \vec{b} = \sum\limits_{i=1}^{n} a_i b_i $

### In contrast, if $ \vec{a}$ and  $ \vec{b}$ are 3-dimensional vectors, with $\vec{x}$, $\vec{y}$ and $\vec{z}$ as unit vectors along the x, y and z axes :

$ \vec{a} = (a_1\ ,   a_2\ ,  a_3)=a_1\vec{x}+a_2\vec{y}+a_3\vec{z}$
$ \\ $
$ \vec{b} = (b_1\ ,   b_2\ , b_3)=b_1\vec{x}+b_2\vec{y}+b_3\vec{z}$
$ \\ $

### then their cross-product, $\vec{a} \times \vec{b}$ is defined as a vector which is perpendicular to both $ \vec{a}$ and  $ \vec{b}$ and is expressed as follows:

$\vec{a} \times \vec{b} =\begin{pmatrix} \vec{x} & \vec{y} & \vec{z} \\ a_1\ & a_2\ & a_3\ \\ b_1\ & b_2\ & b_3\ \end{pmatrix} = \vec{x} (a_2 b_3-a_3 b_2) + \vec{y} (a_3 b_1-a_1 b_3) + \vec{z} (a_1 b_2-a_2 b_1) = (a_2 b_3-a_3 b_2 ,  a_3 b_1-a_1 b_3 ,  a_1 b_2-a_2 b_1) .  $ 

# Q2

In [2]:
from numpy import linalg as LA
def angle_between(v1,v2):
    try:
        th=np.arccos(np.dot(v1, v2)/(LA.norm(v1)*LA.norm(v2)))
    except Exception as e:
        print(e)
    else:
        return (th)

In [4]:
a1=[2,3,4,9]
b1=[5,6,7]
a2=[1,6,8]
b2=[1,5,6,7]
c='c'
d=True
e= False

In [7]:
angle_between(b1,a2)

0.40202939638014745

In [8]:
angle_between(b1,a1)

shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)


In [9]:
angle_between(b1,c)

ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None


In [10]:
# don't know how to throw an error if I want to measure the angle between a vector and a boolean
angle_between(b1,d)

array([1.07386384, 0.96175972, 0.84005239])

# Q3

In [15]:
def row_dot(A, r1, r2):
    try:
        product =(np.dot(A[r1], A[r2]))
    except NameError:
        return "NameError occurred. Some variable isn't defined."
    except IndexError:
        return "Index out of range"
    else:
        print(product)

In [11]:
np.random.seed(1)
M1=np.random.randint(1, 10, size=(5, 7), dtype=int)
M1

array([[6, 9, 6, 1, 1, 2, 8],
       [7, 3, 5, 6, 3, 5, 3],
       [5, 8, 8, 2, 8, 1, 7],
       [8, 7, 2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7, 6, 2]])

In [14]:
row_dot(M1, 1, 2)

161


In [16]:
row_dot(M1, 1, 89)

'Index out of range'

In [17]:
row_dot(M1, 1, 'c')

'Index out of range'

In [18]:
row_dot(M1, 1, a)

NameError: name 'a' is not defined

# Q4

### Problem with matrix division: If $A$ and $B$ are two matrices, then the following criteria should be met to define their quotient: 
### 1. $B$ should be a square matrix.
### 2. $det(B) \neq 0$.
### 3. If the number of columns in $A$ is equal to the number of rows in $B$, then   $ \frac{A}{B} =  A  \cdot B^{-1} $.
### 4. If the number of columns in $B$ is equal to the number of rows in $A$, then   $ \frac{A}{B} =  B^{-1}  \cdot A $.
### 5. If both criteria 3. and 4. are met (i.e. $A$ and $B$ are square matrices of the same size), then \frac{A}{B} is ambiguous.

In [19]:
def m_divide_left(A,B):
    if (type(A) != np.ndarray or type(B) != np.ndarray):
        print('Input should be matrices')
    elif (B.shape[0]!=B.shape[1]):
        print('Second matrix should be square matrix')
    elif (det(B)==0):
        print('Determinant of second matrix is zero')
    elif (A.shape[1] != B.shape[0]):
        print('Matrix sizes do not match')
    else:
        print('A*B^(-1)= \n', np.dot(A, LA.inv(B)))

In [20]:
def m_divide_right(A,B):
    if (type(A) != np.ndarray or type(B) != np.ndarray):
        print('Input should be matrices')
    elif (B.shape[0]!=B.shape[1]):
        print('Second matrix should be square matrix')
    elif (det(B)==0):
        print('Determinant of second matrix is zero')
    elif (B.shape[1] != A.shape[0]):
        print('Matrix sizes do not match')
    else:
        print('B^(-1)*A= \n', np.dot(LA.inv(B), A))

In [21]:
def matrix_division(m1,m2):
    return(m_divide_left(m1,m2),  m_divide_right(m1,m2))

In [26]:
np.random.seed(1)
M2=np.random.randint(1, 10, size=(5, 7), dtype=int)
M3=np.random.randint(1, 10, size=(7, 7), dtype=int)
M8=np.random.randint(1, 10, size=(7, 5), dtype=int)
M9=np.random.randint(1, 10, size=(7, 7), dtype=int)
A='a'

In [27]:
m_divide_left(M2,A)

Input should be matrices


In [23]:
m_divide_left(M2,M3)

A*B^(-1)= 
 [[ 0.78535454 -2.65537573 -2.2035439   1.91795903 -0.36833216  4.13496914
  -0.74758161]
 [-0.21091423 -1.05907011  0.04174984  0.77803028  0.09833246  1.70458803
  -0.64309185]
 [ 0.9091607  -1.29524307 -1.86073151  1.32024076  0.57700458  1.95940178
  -0.37103461]
 [ 0.15347173 -1.00998065 -0.26250653  1.27741609 -0.92463839  2.32856309
  -0.76800356]
 [ 1.23626509  4.98088321  5.64335289 -3.28017996 -1.17873046 -8.77067531
   2.45590087]]


In [24]:
m_divide_right(M2,M3)

Matrix sizes do not match


In [25]:
matrix_division(M2,M3)

A*B^(-1)= 
 [[ 0.78535454 -2.65537573 -2.2035439   1.91795903 -0.36833216  4.13496914
  -0.74758161]
 [-0.21091423 -1.05907011  0.04174984  0.77803028  0.09833246  1.70458803
  -0.64309185]
 [ 0.9091607  -1.29524307 -1.86073151  1.32024076  0.57700458  1.95940178
  -0.37103461]
 [ 0.15347173 -1.00998065 -0.26250653  1.27741609 -0.92463839  2.32856309
  -0.76800356]
 [ 1.23626509  4.98088321  5.64335289 -3.28017996 -1.17873046 -8.77067531
   2.45590087]]
Matrix sizes do not match


(None, None)

In [28]:
matrix_division(M8,M9)

Matrix sizes do not match
B^(-1)*A= 
 [[ 3.19705187  2.10932906 -0.86112987  1.25912717  1.18928938]
 [-1.87154434 -1.83239775  1.32281687 -0.66433124 -0.31714008]
 [-0.77720213 -0.56054531  1.00199426 -0.07970709 -0.40507745]
 [ 0.5907652   0.47393745 -0.34237961  0.58907694 -0.09019542]
 [-0.96596041 -0.73429564  0.33788461 -0.93322922 -0.8221697 ]
 [-0.19288397  0.06228281 -0.17127422  0.21061073 -0.10996215]
 [ 0.47103575  0.83694199  0.02898535  0.38118854  1.37699602]]


(None, None)

In [29]:
matrix_division(M3,M9)

A*B^(-1)= 
 [[-0.06380225  0.564773    0.44195895 -0.4329584   0.48300834 -1.42022257
   0.88680904]
 [ 0.35339552 -0.64620352 -0.69957371  1.38147343  0.66324442  0.03452497
  -0.04294517]
 [ 0.67752782  0.20532787  0.14534532 -0.16082458  0.39284106  0.25338004
  -0.00384783]
 [-0.13304914  0.19306687 -0.8638135   2.11593438 -0.1664697  -0.27057218
  -0.24453073]
 [ 0.97153871 -0.22479917  1.52284078 -1.18078828  0.54710604 -0.5197597
  -0.02381153]
 [ 0.4097272  -0.21684323 -0.09772225  0.10348345  0.75426638  0.3296895
   0.16162298]
 [-0.32164212 -0.01624249  0.1404775   0.86261413  0.82905992 -0.5105024
  -0.23622308]]
B^(-1)*A= 
 [[-1.33819412e-01 -4.90820073e-01  2.38543030e+00  1.18997524e+00
   6.55256827e-02  1.28918527e+00  2.22248484e+00]
 [-1.16257966e-01  4.58996328e-01 -2.41814038e+00 -1.21388174e+00
   1.72835859e-01 -5.06478707e-04 -5.19436120e-01]
 [-2.26448740e-01 -1.32190942e-01  7.73941671e-01  6.62632423e-01
   3.15050859e-01 -6.81509307e-01 -5.27919639e-01]
 [ 5

(None, None)

In [30]:
matrix_division(M2,a)

NameError: name 'a' is not defined

# Q5

In [1]:
def my_is_orthogonal(v1,v2, tol):
    a=v1.reshape(-1)
    b=v2.reshape(-1)
    th=arccos(dot(a, b.T)/(norm(a)*norm(b)))
    if np.abs(np.pi/2-th)<tol:
        return(1)
    else:
        return(0)


# q6

In [ ]:
class vector_calculator():
    def __init__(self, v1, v2):
        

    def angle_between(v1,v2):
        try:
            th=np.arccos(np.dot(v1, v2)/(LA.norm(v1)*LA.norm(v2)))
        except Exception as e:
            print(e)
        else:
            return (th)
        
    def my_is_orthogonal(v1,v2, tol=0.001):
    a=v1.reshape(-1)
    b=v2.reshape(-1)
    th=arccos(dot(a, b.T)/(norm(a)*norm(b)))
    if np.abs(np.pi/2-th)<tol:
        return(1)
    else:
        return(0)
# i dont know what i am doing