### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [ ]:
dir(np.array)


In [ ]:
#output:
['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [ ]:
dir(car)

In [ ]:
['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__xor__',
 'all',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'astype',
 'base',
 'byteswap',
 'choose',
 'clip',
 'compress',
 'conj',
 'conjugate',
 'copy',
 'ctypes',
 'cumprod',
 'cumsum',
 'data',
 'diagonal',
 'dot',
 'dtype',
 'dump',
 'dumps',
 'fill',
 'flags',
 'flat',
 'flatten',
 'getfield',
 'imag',
 'item',
 'itemset',
 'itemsize',
 'max',
 'mean',
 'min',
 'nbytes',
 'ndim',
 'newbyteorder',
 'nonzero',
 'partition',
 'prod',
 'ptp',
 'put',
 'ravel',
 'real',
 'repeat',
 'reshape',
 'resize',
 'round',
 'searchsorted',
 'setfield',
 'setflags',
 'shape',
 'size',
 'sort',
 'squeeze',
 'std',
 'strides',
 'sum',
 'swapaxes',
 'take',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'trace',
 'transpose',
 'var',
 'view']

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [6]:
car.dtype
# dtype('O') : string
mpg.dtype
# dtype('float64') float, 64 bits
horsepower.dtype
# dtype('float64')
origin.dtype
# dtype('O') : string

object


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#Modules are imported so that only those objects, pieces of code etc. are used that are required at the moment and not all Python modules.

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [ ]:
car.size

In [ ]:
#406 

In [ ]:
horsepower.size

In [ ]:
406


In [ ]:
mpg.size

In [ ]:
406

In [ ]:
cylinders.size

In [7]:
406


1

5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [ ]:
print(mpg*12)

In [ ]:
[216.  180.  216.  192.  204.  180.  168.  168.  168.  180.    0.    0.
   0.    0.    0.  180.  168.    0.  180.  168.  288.  264.  216.  252.
 324.  312.  300.  288.  300.  312.  252.  120.  120.  132.  108.  324.
 336.  300.  300.    0.  228.  192.  204.  228.  216.  168.  168.  168.
 168.  144.  156.  156.  216.  264.  228.  216.  276.  336.  360.  360.
 372.  420.  324.  312.  288.  300.  276.  240.  252.  156.  168.  180.
 168.  204.  132.  156.  144.  156.  228.  180.  156.  156.  168.  216.
 264.  252.  312.  264.  336.  276.  336.  324.  156.  168.  156.  168.
 180.  144.  156.  156.  168.  156.  144.  156.  216.  192.  216.  216.
 276.  312.  132.  144.  156.  144.  216.  240.  252.  264.  216.  228.
 252.  312.  180.  192.  348.  288.  240.  228.  180.  288.  240.  132.
 240.  252.  228.  180.  372.  312.  384.  300.  192.  192.  216.  192.
 156.  168.  168.  168.  348.  312.  312.  372.  384.  336.  288.  312.
 288.  312.  372.  228.  216.  180.  180.  192.  180.  192.  168.  204.
 192.  180.  216.  252.  240.  156.  348.  276.  240.  276.  288.  300.
 288.  216.  348.  228.  276.  276.  264.  300.  396.  336.  300.  300.
 312.  324.  210.  192.  186.  174.  264.  264.  288.  270.  348.  294.
 348.  396.  240.  216.  222.  210.  354.  384.  336.  318.  240.  156.
 228.  228.  198.  198.  156.  156.  156.  378.  360.  432.  306.  402.
 210.  204.  186.  180.  210.  246.  228.  222.  192.  186.  186.  192.
 348.  294.  312.  306.  366.  402.  360.  366.  264.  258.  258.  517.2
 433.2 393.6 472.8 433.2 238.8 232.8 242.4 230.4 246.  242.4 301.2 246.
 232.8 247.2 249.6 223.2 217.2 230.4 212.4 217.2 210.  360.  330.  326.4
 370.8 253.2 278.4 285.6 286.8 243.6 204.  259.2 194.4 378.  354.  258.
 237.6 267.6 242.4 247.2 204.  211.2 198.  218.4 202.8 186.  230.4 222.
 382.8 409.2 428.4 328.8 304.8 276.  326.4 286.8 410.4 414.  381.6 447.6
 340.8 345.6 321.6 402.  498.  457.2 385.2 446.4 336.  316.8 291.6 229.2
 411.6 357.6 375.6 444.  386.4 559.2 334.8 489.6 531.6 520.8 436.8 360.
 535.2 490.8 405.6 357.6 392.4 284.4 420.  283.2 388.8 326.4 319.2 309.6
 282.  360.  469.2 468.  421.2 387.6 444.  452.4 409.2 416.4 412.8 358.8
 396.  414.  404.4 388.8 394.8 379.2 337.2   0.  368.4 304.8 290.4 268.8
 319.2 242.4 211.2 336.  324.  408.  372.  348.  324.  288.  276.  432.
 444.  372.  456.  432.  432.  432.  408.  456.  384.  456.  300.  456.
 312.  264.  384.  432.  324.  324.  528.  384.  336.  372. ]

In [ ]:
print(mpg/3)

In [ ]:
[ 6.          5.          6.          5.33333333  5.66666667  5.
  4.66666667  4.66666667  4.66666667  5.          0.          0.
  0.          0.          0.          5.          4.66666667  0.
  5.          4.66666667  8.          7.33333333  6.          7.
  9.          8.66666667  8.33333333  8.          8.33333333  8.66666667
  7.          3.33333333  3.33333333  3.66666667  3.          9.
  9.33333333  8.33333333  8.33333333  0.          6.33333333  5.33333333
  5.66666667  6.33333333  6.          4.66666667  4.66666667  4.66666667
  4.66666667  4.          4.33333333  4.33333333  6.          7.33333333
  6.33333333  6.          7.66666667  9.33333333 10.         10.
 10.33333333 11.66666667  9.          8.66666667  8.          8.33333333
  7.66666667  6.66666667  7.          4.33333333  4.66666667  5.
  4.66666667  5.66666667  3.66666667  4.33333333  4.          4.33333333
  6.33333333  5.          4.33333333  4.33333333  4.66666667  6.
  7.33333333  7.          8.66666667  7.33333333  9.33333333  7.66666667
  9.33333333  9.          4.33333333  4.66666667  4.33333333  4.66666667
  5.          4.          4.33333333  4.33333333  4.66666667  4.33333333
  4.          4.33333333  6.          5.33333333  6.          6.
  7.66666667  8.66666667  3.66666667  4.          4.33333333  4.
  6.          6.66666667  7.          7.33333333  6.          6.33333333
  7.          8.66666667  5.          5.33333333  9.66666667  8.
  6.66666667  6.33333333  5.          8.          6.66666667  3.66666667
  6.66666667  7.          6.33333333  5.         10.33333333  8.66666667
 10.66666667  8.33333333  5.33333333  5.33333333  6.          5.33333333
  4.33333333  4.66666667  4.66666667  4.66666667  9.66666667  8.66666667
  8.66666667 10.33333333 10.66666667  9.33333333  8.          8.66666667
  8.          8.66666667 10.33333333  6.33333333  6.          5.
  5.          5.33333333  5.          5.33333333  4.66666667  5.66666667
  5.33333333  5.          6.          7.          6.66666667  4.33333333
  9.66666667  7.66666667  6.66666667  7.66666667  8.          8.33333333
  8.          6.          9.66666667  6.33333333  7.66666667  7.66666667
  7.33333333  8.33333333 11.          9.33333333  8.33333333  8.33333333
  8.66666667  9.          5.83333333  5.33333333  5.16666667  4.83333333
  7.33333333  7.33333333  8.          7.5         9.66666667  8.16666667
  9.66666667 11.          6.66666667  6.          6.16666667  5.83333333
  9.83333333 10.66666667  9.33333333  8.83333333  6.66666667  4.33333333
  6.33333333  6.33333333  5.5         5.5         4.33333333  4.33333333
  4.33333333 10.5        10.         12.          8.5        11.16666667
  5.83333333  5.66666667  5.16666667  5.          5.83333333  6.83333333
  6.33333333  6.16666667  5.33333333  5.16666667  5.16666667  5.33333333
  9.66666667  8.16666667  8.66666667  8.5        10.16666667 11.16666667
 10.         10.16666667  7.33333333  7.16666667  7.16666667 14.36666667
 12.03333333 10.93333333 13.13333333 12.03333333  6.63333333  6.46666667
  6.73333333  6.4         6.83333333  6.73333333  8.36666667  6.83333333
  6.46666667  6.86666667  6.93333333  6.2         6.03333333  6.4
  5.9         6.03333333  5.83333333 10.          9.16666667  9.06666667
 10.3         7.03333333  7.73333333  7.93333333  7.96666667  6.76666667
  5.66666667  7.2         5.4        10.5         9.83333333  7.16666667
  6.6         7.43333333  6.73333333  6.86666667  5.66666667  5.86666667
  5.5         6.06666667  5.63333333  5.16666667  6.4         6.16666667
 10.63333333 11.36666667 11.9         9.13333333  8.46666667  7.66666667
  9.06666667  7.96666667 11.4        11.5        10.6        12.43333333
  9.46666667  9.6         8.93333333 11.16666667 13.83333333 12.7
 10.7        12.4         9.33333333  8.8         8.1         6.36666667
 11.43333333  9.93333333 10.43333333 12.33333333 10.73333333 15.53333333
  9.3        13.6        14.76666667 14.46666667 12.13333333 10.
 14.86666667 13.63333333 11.26666667  9.93333333 10.9         7.9
 11.66666667  7.86666667 10.8         9.06666667  8.86666667  8.6
  7.83333333 10.         13.03333333 13.         11.7        10.76666667
 12.33333333 12.56666667 11.36666667 11.56666667 11.46666667  9.96666667
 11.         11.5        11.23333333 10.8        10.96666667 10.53333333
  9.36666667  0.         10.23333333  8.46666667  8.06666667  7.46666667
  8.86666667  6.73333333  5.86666667  9.33333333  9.         11.33333333
 10.33333333  9.66666667  9.          8.          7.66666667 12.
 12.33333333 10.33333333 12.66666667 12.         12.         12.
 11.33333333 12.66666667 10.66666667 12.66666667  8.33333333 12.66666667
  8.66666667  7.33333333 10.66666667 12.          9.          9.
 14.66666667 10.66666667  9.33333333 10.33333333]

In [ ]:

print(mpg**4)

In [ ]:
[ 104976.       50625.      104976.       65536.       83521.
   50625.       38416.       38416.       38416.       50625.
       0.           0.           0.           0.           0.
   50625.       38416.           0.       50625.       38416.
  331776.      234256.      104976.      194481.      531441.
  456976.      390625.      331776.      390625.      456976.
  194481.       10000.       10000.       14641.        6561.
  531441.      614656.      390625.      390625.           0.
  130321.       65536.       83521.      130321.      104976.
   38416.       38416.       38416.       38416.       20736.
   28561.       28561.      104976.      234256.      130321.
  104976.      279841.      614656.      810000.      810000.
  923521.     1500625.      531441.      456976.      331776.
  390625.      279841.      160000.      194481.       28561.
   38416.       50625.       38416.       83521.       14641.
   28561.       20736.       28561.      130321.       50625.
   28561.       28561.       38416.      104976.      234256.
  194481.      456976.      234256.      614656.      279841.
  614656.      531441.       28561.       38416.       28561.
   38416.       50625.       20736.       28561.       28561.
   38416.       28561.       20736.       28561.      104976.
   65536.      104976.      104976.      279841.      456976.
   14641.       20736.       28561.       20736.      104976.
  160000.      194481.      234256.      104976.      130321.
  194481.      456976.       50625.       65536.      707281.
  331776.      160000.      130321.       50625.      331776.
  160000.       14641.      160000.      194481.      130321.
   50625.      923521.      456976.     1048576.      390625.
   65536.       65536.      104976.       65536.       28561.
   38416.       38416.       38416.      707281.      456976.
  456976.      923521.     1048576.      614656.      331776.
  456976.      331776.      456976.      923521.      130321.
  104976.       50625.       50625.       65536.       50625.
   65536.       38416.       83521.       65536.       50625.
  104976.      194481.      160000.       28561.      707281.
  279841.      160000.      279841.      331776.      390625.
  331776.      104976.      707281.      130321.      279841.
  279841.      234256.      390625.     1185921.      614656.
  390625.      390625.      456976.      531441.       93789.0625
   65536.       57720.0625   44205.0625  234256.      234256.
  331776.      256289.0625  707281.      360300.0625  707281.
 1185921.      160000.      104976.      117135.0625   93789.0625
  757335.0625 1048576.      614656.      493155.0625  160000.
   28561.      130321.      130321.       74120.0625   74120.0625
   28561.       28561.       28561.      984560.0625  810000.
 1679616.      422825.0625 1259445.0625   93789.0625   83521.
   57720.0625   50625.       93789.0625  176610.0625  130321.
  117135.0625   65536.       57720.0625   57720.0625   65536.
  707281.      360300.0625  456976.      422825.0625  865365.0625
 1259445.0625  810000.      865365.0625  234256.      213675.0625
  213675.0625 3450714.9121 1698356.3041 1157431.7056 2409821.5696
 1698356.3041  156823.9201  141646.8496  166496.6416  135895.4496
  176610.0625  166496.6416  396912.6001  176610.0625  141646.8496
  180081.4096  187177.3696  119688.3216  107328.3121  135895.4496
   98150.6241  107328.3121   93789.0625  810000.      571914.0625
  547363.2256  911662.1361  198211.9441  289702.2976  320854.2736
  326280.8641  169818.1681   83521.      217678.2336   68874.7536
  984560.0625  757335.0625  213675.0625  153695.3616  247297.3441
  166496.6416  180081.4096   83521.       95951.2576   74120.0625
  109719.9376   81573.0721   57720.0625  135895.4496  117135.0625
 1035530.1121 1352127.0961 1624324.7601  563640.5776  416231.4256
  279841.      547363.2256  326280.8641 1368057.7296 1416695.0625
 1022606.3376 1935687.8641  650539.0336  687970.7136  515868.6976
 1259445.0625 2966145.0625 2107171.5921 1061744.7681 1915013.1456
  614656.      485753.2416  348678.4401  133086.3361 1384128.7201
  788615.0416  959792.4961 1874161.     1075037.1856 4715672.8336
  605922.1281 2771026.3296 3851367.0001 3547798.2736 1755519.0016
  810000.     3956757.5056 2798293.2961 1305169.1536  788615.0416
 1143381.1041  315495.6561 1500625.      310204.4416 1101996.0576
  547363.2256  500641.1536  443076.6096  304980.0625  810000.
 2337260.0161 2313441.     1517848.6401 1088454.0241 1874161.
 2020065.2641 1352127.0961 1449832.7281 1400340.8896  799253.8801
 1185921.     1416695.0625 1289791.7761 1101996.0576 1171611.4081
  997122.0736  623483.9521       0.      888287.4001  416231.4256
  342974.2096  251763.0976  500641.1536  166496.6416   95951.2576
  614656.      531441.     1336336.      923521.      707281.
  531441.      331776.      279841.     1679616.     1874161.
  923521.     2085136.     1679616.     1679616.     1679616.
 1336336.     2085136.     1048576.     2085136.      390625.
 2085136.      456976.      234256.     1048576.     1679616.
  531441.      531441.     3748096.     1048576.      614656.
  923521.    ]

In [ ]:
print(mpg**0.5)

In [ ]:
[4.24264069 3.87298335 4.24264069 4.         4.12310563 3.87298335
 3.74165739 3.74165739 3.74165739 3.87298335 0.         0.
 0.         0.         0.         3.87298335 3.74165739 0.
 3.87298335 3.74165739 4.89897949 4.69041576 4.24264069 4.58257569
 5.19615242 5.09901951 5.         4.89897949 5.         5.09901951
 4.58257569 3.16227766 3.16227766 3.31662479 3.         5.19615242
 5.29150262 5.         5.         0.         4.35889894 4.
 4.12310563 4.35889894 4.24264069 3.74165739 3.74165739 3.74165739
 3.74165739 3.46410162 3.60555128 3.60555128 4.24264069 4.69041576
 4.35889894 4.24264069 4.79583152 5.29150262 5.47722558 5.47722558
 5.56776436 5.91607978 5.19615242 5.09901951 4.89897949 5.
 4.79583152 4.47213595 4.58257569 3.60555128 3.74165739 3.87298335
 3.74165739 4.12310563 3.31662479 3.60555128 3.46410162 3.60555128
 4.35889894 3.87298335 3.60555128 3.60555128 3.74165739 4.24264069
 4.69041576 4.58257569 5.09901951 4.69041576 5.29150262 4.79583152
 5.29150262 5.19615242 3.60555128 3.74165739 3.60555128 3.74165739
 3.87298335 3.46410162 3.60555128 3.60555128 3.74165739 3.60555128
 3.46410162 3.60555128 4.24264069 4.         4.24264069 4.24264069
 4.79583152 5.09901951 3.31662479 3.46410162 3.60555128 3.46410162
 4.24264069 4.47213595 4.58257569 4.69041576 4.24264069 4.35889894
 4.58257569 5.09901951 3.87298335 4.         5.38516481 4.89897949
 4.47213595 4.35889894 3.87298335 4.89897949 4.47213595 3.31662479
 4.47213595 4.58257569 4.35889894 3.87298335 5.56776436 5.09901951
 5.65685425 5.         4.         4.         4.24264069 4.
 3.60555128 3.74165739 3.74165739 3.74165739 5.38516481 5.09901951
 5.09901951 5.56776436 5.65685425 5.29150262 4.89897949 5.09901951
 4.89897949 5.09901951 5.56776436 4.35889894 4.24264069 3.87298335
 3.87298335 4.         3.87298335 4.         3.74165739 4.12310563
 4.         3.87298335 4.24264069 4.58257569 4.47213595 3.60555128
 5.38516481 4.79583152 4.47213595 4.79583152 4.89897949 5.
 4.89897949 4.24264069 5.38516481 4.35889894 4.79583152 4.79583152
 4.69041576 5.         5.74456265 5.29150262 5.         5.
 5.09901951 5.19615242 4.18330013 4.         3.93700394 3.80788655
 4.69041576 4.69041576 4.89897949 4.74341649 5.38516481 4.94974747
 5.38516481 5.74456265 4.47213595 4.24264069 4.30116263 4.18330013
 5.43139025 5.65685425 5.29150262 5.14781507 4.47213595 3.60555128
 4.35889894 4.35889894 4.0620192  4.0620192  3.60555128 3.60555128
 3.60555128 5.61248608 5.47722558 6.         5.04975247 5.78791845
 4.18330013 4.12310563 3.93700394 3.87298335 4.18330013 4.52769257
 4.35889894 4.30116263 4.         3.93700394 3.93700394 4.
 5.38516481 4.94974747 5.09901951 5.04975247 5.52268051 5.78791845
 5.47722558 5.52268051 4.69041576 4.63680925 4.63680925 6.56505902
 6.00832755 5.72712843 6.27694193 6.00832755 4.4609416  4.40454311
 4.49444101 4.38178046 4.52769257 4.49444101 5.00999002 4.52769257
 4.40454311 4.53872229 4.5607017  4.31277173 4.25440948 4.38178046
 4.20713679 4.25440948 4.18330013 5.47722558 5.24404424 5.21536192
 5.55877684 4.59347363 4.81663783 4.87852437 4.88876262 4.50555213
 4.12310563 4.64758002 4.02492236 5.61248608 5.43139025 4.63680925
 4.44971909 4.72228758 4.49444101 4.53872229 4.12310563 4.19523539
 4.0620192  4.2661458  4.11096096 3.93700394 4.38178046 4.30116263
 5.6480085  5.83952053 5.9749477  5.23450093 5.03984127 4.79583152
 5.21536192 4.88876262 5.84807661 5.87367006 5.63914887 6.10737259
 5.32916504 5.36656315 5.17687164 5.78791845 6.44204936 6.17251974
 5.66568619 6.09918027 5.29150262 5.13809303 4.92950302 4.37035468
 5.85662019 5.45893763 5.59464029 6.08276253 5.67450438 6.82641927
 5.28204506 6.38748777 6.65582452 6.58786764 6.03324125 5.47722558
 6.67832314 6.39531078 5.81377674 5.45893763 5.71839138 4.86826458
 5.91607978 4.85798312 5.69209979 5.21536192 5.15751878 5.07937004
 4.84767986 5.47722558 6.25299928 6.244998   5.9245253  5.6833089
 6.08276253 6.14003257 5.83952053 5.89067059 5.86515132 5.46808925
 5.74456265 5.87367006 5.80517011 5.69209979 5.73585216 5.62138773
 5.30094331 0.         5.54075807 5.03984127 4.91934955 4.73286383
 5.15751878 4.49444101 4.19523539 5.29150262 5.19615242 5.83095189
 5.56776436 5.38516481 5.19615242 4.89897949 4.79583152 6.
 6.08276253 5.56776436 6.164414   6.         6.         6.
 5.83095189 6.164414   5.65685425 6.164414   5.         6.164414
 5.09901951 4.69041576 5.65685425 6.         5.19615242 5.19615242
 6.63324958 5.65685425 5.29150262 5.56776436]



6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [ ]:
horsepower.sum()
# the result: 42033.0
horsepower.min()
# the result: 0.0
horsepower.max()
# the result: 230.0
np.median(horsepower)
# the result: 93.5
from scipy import stats
print(stats.mode(horsepower)[0])
# the result: [150.]

7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [ ]:
print(acceleration[0:5])

In [ ]:
[12.  11.5 11.  12.  10.5]

In [ ]:

print(acceleration[0::2])

In [ ]:
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 14.7 14.5 16.9
 15.7 16.4 14.5 13.9 17.3 24.6 18.6]
​

8.Show how to select the number `99` in the array below. 

In [19]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [ ]:
select_99[1][2]

9.Select the last element in each subarray (do this with one operation.)

In [21]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [ ]:
select_more.transpose()[-1]

10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [ ]:
np.lookfor('log')
np.log(mpg)
#this gives an error for values which are equal to 0. To fix this :
np.log(mpg[mpg>0])


11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [26]:
#type(origin)
origin_test = [0,6,5,0,6,5]
np.unique(origin)
#output: array(['Europe', 'Japan', 'US'], dtype=object)

array([0, 5, 6])

12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [ ]:
#Creating a 2D array:
np.arange(7,35,2).reshape(2,7)
#output:array([[ 7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33]])
#determining its dimensions:
np.ndim(np.arange(7,35,2).reshape(2,7))
#output:2
np.arange(7,35,2).reshape(2,7).shape
#output:(2, 7)


​#Creating a 3D array:
array3d=np.arange(7,55,2)
array3d_reshaped=array3d.reshape(3,4,2)
array3d_reshaped
#output:array([[[ 7,  9],
        [11, 13],
        [15, 17],
        [19, 21]],

       [[23, 25],
        [27, 29],
        [31, 33],
        [35, 37]],

       [[39, 41],
        [43, 45],
        [47, 49],
        [51, 53]]])
#determining its dimensions:
np.ndim(array3d_reshaped)
#output:3
array3d_reshaped.shape
#output:(3, 4, 2)

​#Creating a 4D array:
array4d=np.arange(7,367,3)
array4d_reshaped=array4d.reshape(2,3,4,5)
array4d_reshaped
# output:
array([[[[  7,  10,  13,  16,  19],
         [ 22,  25,  28,  31,  34],
         [ 37,  40,  43,  46,  49],
         [ 52,  55,  58,  61,  64]],

        [[ 67,  70,  73,  76,  79],
         [ 82,  85,  88,  91,  94],
         [ 97, 100, 103, 106, 109],
         [112, 115, 118, 121, 124]],

        [[127, 130, 133, 136, 139],
         [142, 145, 148, 151, 154],
         [157, 160, 163, 166, 169],
         [172, 175, 178, 181, 184]]],


       [[[187, 190, 193, 196, 199],
         [202, 205, 208, 211, 214],
         [217, 220, 223, 226, 229],
         [232, 235, 238, 241, 244]],

        [[247, 250, 253, 256, 259],
         [262, 265, 268, 271, 274],
         [277, 280, 283, 286, 289],
         [292, 295, 298, 301, 304]],

        [[307, 310, 313, 316, 319],
         [322, 325, 328, 331, 334],
         [337, 340, 343, 346, 349],
         [352, 355, 358, 361, 364]]]])
#determining its dimensions:
np.ndim(array4d_reshaped)
#output:4
array4d_reshaped.shape
#output:(2, 3, 4, 5)

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [31]:
is_US=origin=='US'
is_US

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [32]:
car[is_US]

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
#Advantage of using np.array: faster (the subsequent items in an np array refer to contiguous pieces of memory ); the items of the np array have the same  type, thus it occupies less memory
#Advantage of lists: items don't have to have the same data type; lists don't have to be declared (i.e. stated that they are lists)

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [ ]:
# an identity matrix is an n*n matrix M, where the M(j,k)=1 if j=k and M(j,k)=0 otherwise (1<=j,k<=n)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

17.Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [ ]:
transpose_me .transpose()

In [ ]:

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

In [ ]:
#because the number of lines in arr2 does not  divide that of arr1. In contrast, if either arr1 or arr2 are changed so that the number of lines of one divides that of the other, the multiplication becomes possible.
arr0= np.array([7,9,11])
arr1*arr0
#output: 
      array([[ 7, 18, 33],
       [28, 45, 66],
       [49, 72, 99]])


Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [ ]:
eur_cars_horsepower=horsepower[origin=='Europe']
np.average(eur_cars_horsepower)
#output:78.78082191780823

3.On average are Japanse cars more fuel efficient than US cars? 

In [ ]:
eur_cars_mpg=mpg[origin=='Europe']
np.average(eur_cars_mpg)
#output: 26.745205479452054
jpn_cars_mpg=mpg[origin=='Japan']
np.average(jpn_cars_mpg)
#output:30.450632911392404
np.average(jpn_cars_mpg)>np.average(eur_cars_mpg)
# output: True

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?

In [ ]:
np.corrcoef(mpg, weight)
#output: 
array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])
#The correlation coefficient is -0.7875. A correlation coefficient shows 